# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_collector_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
