# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170827_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
