# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20170827_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
