from decouple import config


AWS_UPLOAD_BUCKET = config('AWS_UPLOAD_BUCKET')

AWS_UPLOAD_USERNAME = config('AWS_UPLOAD_USERNAME')

AWS_UPLOAD_GROUP = config('AWS_UPLOAD_GROUP')

AWS_UPLOAD_REGION = config('AWS_UPLOAD_REGION')

AWS_UPLOAD_ACCESS_KEY_ID = config('AWS_UPLOAD_ACCESS_KEY_ID')

AWS_UPLOAD_SECRET_KEY = config('AWS_UPLOAD_SECRET_KEY')
