language: python

python:
  - 3.4
  - 3.5

services: postgresql

env:
  - DJANGO=1.10
  - DJANGO=1.11

before_install:
  - export DJANGO_SETTINGS_MODULE="duka.settings"
  - export PYTHONPATH="/home/travis/builds/kipkemei/duka"
  - export PIP_USE_MIRRORS=true

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

install:
  - pip install --upgrade pip wheel setuptools
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet
  - cp .env-example .env

script:
  - python manage.py migrate --noinput

notifications:
  email:
    on_success: change
    on_failure: always