# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('age_bracket', models.CharField(blank=True, choices=[('<<10', 'CHILD'), ('10-20', 'TEENAGER'), ('20-30', 'TWENTIES'), ('30-40', 'THIRTIES'), ('40-50', 'FORTIES'), ('50-60', 'FIFTIES'), ('60-70', 'SIXTIES'), ('70>>', 'OLD')], max_length=5, null=True)),
                ('location', geoposition.fields.GeopositionField(blank=True, max_length=42, null=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
            options={
                'verbose_name_plural': "People's Favourite",
                'verbose_name': "Person's Favourite",
            },
        ),
    ]
