# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 15:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_auto_20170827_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 27, 15, 59, 9, 201712, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 27, 15, 59, 22, 979200, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
