# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_auto_20170827_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
