# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 19:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0005_auto_20170827_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 27, 19, 15, 16, 61169, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorite',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 8, 27, 19, 15, 27, 453491, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
