# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0006_auto_20170827_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
